services:
  peerprep_mongo:
    image: mongo:8.0.14-noble
    restart: unless-stopped
    container_name: "peerprep_mongo"
    ports:
      - "127.0.0.1:27017:27017" # bind to localhost of the host only - prevents external access
    volumes:
      - mongo_data:/data/db # Use a named volume called "mongo_data", and mount it to /data/db for reading by MongoDB

  peerprep_redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    container_name: "peerprep_redis"
    ports:
      - "127.0.0.1:6379:6379" # bind to localhost of the host only - prevents external access
    volumes:
      - redis_data:/data # Use a named volume for Redis data persistence
    command: >
      redis-server 
      --appendonly yes 
      --notify-keyspace-events KEA
      --maxmemory 4gb
      --maxmemory-policy allkeys-lfu

volumes:
  mongo_data:
  redis_data: